### ISSUE TITLE
Error when importing world downtime activities

### ISSUE THREAD

**Issue by Pyroman2xxx** [Ethck/Ethck-s-Downtime-Tracking#49]
Cannot import previously exported World Downtime Activities.

Error in console:

> foundry.js:4503 Foundry VTT | Rendering GMConfig
gmConfig.js:71 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at gmConfig.js:71
(anonymous) @ gmConfig.js:71
load (async)
(anonymous) @ foundry.js:4040
readTextFromFile @ foundry.js:4039
importWorldActivities @ gmConfig.js:66
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

I thought it may have something to do with missing complications tables but they are all there and named the same.
Foundry 0.7.9
DnD5e 1.2.4

**Comment by Ethck** [comment]
I took a look and found the issue. This was caused by some code that didn't get updated, specifically the import code was trying to access properties of the old downtime structure and not the new. This issue is fixed with commit 3aceda54 and should be released here in the near future. Thanks for the report.

**Comment by ctbritt** [comment]
Is there a repository of world downtime activities already done?

**Comment by Ethck** [comment]
@ctbritt due to copyright issues I can not distribute any of the XGE or PHB downtime activities. If you can think of downtime activities that are NOT related to those, then I can definitely look at including some sample downtime activities here in the repo.

**Comment by Pyroman2xxx** [comment]
Importing is still throwing an error but different now:

> Uncaught (in promise) ReferenceError: newDowntimes is not defined
    at gmConfig.js:69
(anonymous) @ gmConfig.js:69
load (async)
(anonymous) @ foundry.js:4040
readTextFromFile @ foundry.js:4039
importWorldActivities @ gmConfig.js:67
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

Any ideas?

**Comment by Ethck** [comment]
Well, that's just fun now isn't it... I'll take a look.

**Comment by Ethck** [comment]
Can you post the file you are trying to import @Pyroman2xxx ?

**Comment by Ethck** [comment]
Try using this version.
[downtime-ethck.zip](https://github.com/Ethck/Ethck-s-Downtime-Tracking/files/6045060/downtime-ethck.zip)

Go to your Foundry User Data/modules/downtime-ethck and replace everything in there with this.

**Comment by Pyroman2xxx** [comment]
> 
> 
> Try using this version.
> [downtime-ethck.zip](https://github.com/Ethck/Ethck-s-Downtime-Tracking/files/6045091/downtime-ethck.zip)
> 
> Go to your Foundry User Data/modules/downtime-ethck and replace everything in there with this (only really need gmConfig.js though)

Tried this and it also does not work. There are no errors in the console with this version. It acts like it does nothing at all when I click the import button and select the file to import. The console shows no related messages.

Here is the file I am trying to import.

[downtime-ethck-world-activities.zip](https://github.com/Ethck/Ethck-s-Downtime-Tracking/files/6046534/downtime-ethck-world-activities.zip)

**Comment by Ethck** [comment]
Try this one. When I imported your activities on this build, they loaded up and worked immediately!
[downtime-ethck.zip](https://github.com/Ethck/Ethck-s-Downtime-Tracking/files/6047131/downtime-ethck.zip)

**Comment by Pyroman2xxx** [comment]
> 
> 
> Try this one. When I imported your activities on this build, they loaded up and worked immediately!
> [downtime-ethck.zip](https://github.com/Ethck/Ethck-s-Downtime-Tracking/files/6047131/downtime-ethck.zip)

This one worked like a charm. :)
